version: '3.8'

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    hostname: swgemu_database
    container_name: swgemu_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root-password
      - MYSQL_USER=swgemu
      - MYSQL_PASSWORD=swgemu-password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

  swgemu:
    depends_on:
      - database
    build: .
    image: swgemu:dev
    hostname: swgemu_server
    container_name: swgemu_server
    deploy:
      resources:
        limits:
          memory: 8192m
    ports:
      - "44419:44419"
      - "44419:44419/udp"
      - "44453:44453"
      - "44453:44453/udp"
      - "44462:44462"
      - "44462:44462/udp"
      - "44463:44463"
      - "44463:44463/udp"
      - "44455:44455"
      - "44455:44455/udp"
      - "44460:44460"
    volumes:
      - ./tre:/tres
      - ./conf:/containeremu/Core3/MMOCoreORB/bin/conf
      - ./custom_scripts:/containeremu/Core3/MMOCoreORB/bin/scripts/custom_scripts
    stop_grace_period: 1m
    restart: always